version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    image: bettermode-api
    container_name: bettermode-server
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=8080
    volumes:
      - api-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/token/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  api-logs: 